# Generated by Django 2.0 on 2018-04-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoax', '0003_auto_20180122_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('corpus', models.TextField()),
                ('label', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hoax',
        ),
    ]
