# Generated by Django 2.0 on 2018-04-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoax', '0004_auto_20180416_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='label',
            field=models.TextField(),
        ),
    ]
