# Generated by Django 2.0 on 2018-01-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoax',
            name='label',
            field=models.IntegerField(),
        ),
    ]
