# Generated by Django 2.0 on 2018-01-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoax', '0002_auto_20180122_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoax',
            name='label',
            field=models.IntegerField(null=True),
        ),
    ]
